services:
  - type: web
    name: tanamao
    env: node
    buildCommand: npm install && npm install --prefix frontend && npm install --prefix server && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: APP_URL
        value: https://tanamao.onrender.com
